### ISSUE TITLE
mauihybrid solution with all plataforms even without maui

### ISSUE THREAD

**Issue by cesarchefinho** [AvaloniaUI/AvaloniaMauiHybrid#12]
Could someone please post the instructions so that a solution with Avalonia Maui Hybrid has Windows and browser projects without Maui Hybrid (use Maui would have to be conditional in the main project, for example) etc etc.

This would allow where Maui is not supported the programmer to create their own solutions.

Thank you very much in advance

**Comment by maxkatz6** [comment]
You have to create separate projects for Windows and browser projects. It's simply a limitation of the SDK.
In .NET 8 it's going to be possible though, but also out of the scope of anything MAUI related. We do have plans to have some single-project support for simple apps.

**Comment by cesarchefinho** [comment]
> You have to create separate projects for Windows and browser projects. It's simply a limitation of the SDK. In .NET 8 it's going to be possible though, but also out of the scope of anything MAUI related. We do have plans to have some single-project support for simple apps.

I dont want an sigle project solution.

I want an solution like avalonia does today, with one project in net7 and other projects one per plataform, but with conditional to use maui hibrid only in android and ios projects and conditional for mai project to only use maui wen target is android and ios but not for windows or browser.

**Comment by CastelloBrancoTecnologia** [comment]
> You have to create separate projects for Windows and browser projects. It's simply a limitation of the SDK. In .NET 8 it's going to be possible though, but also out of the scope of anything MAUI related. We do have plans to have some single-project support for simple apps.

Uno does this, in uno i can have maui/mobile and others plataforms in same solution

**Comment by CastelloBrancoTecnologia** [comment]
This worked for me

change shared project with conditions to use maui only if target is IOS or android

in windows or other platforms projects dont use any maui things, make your api similar to maui essentials yourself

`
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>

	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' or $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
		<UseMaui >true</UseMaui>
		<UseMauiEssentials>true</UseMauiEssentials>
		<SkipValidateMauiImplicitPackageReferences>true</SkipValidateMauiImplicitPackageReferences>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.0.999" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.999" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.999" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />

		
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.999" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' or $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'" >
		<PackageReference Include="Avalonia.Maui" Version="11.0.5" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.3" />
	</ItemGroup>
</Project>

`

**Comment by CastelloBrancoTecnologia** [comment]
THIS WORKED LIKE A SHARM !!!!!!

with this shared project csproject file you also have Browser project compiling in avalonia maui hybrid solution

also note that we are using nuget.config with avalonia nightly builds (see avalonia docs) to get avalonia 11.0.999 
because avalonia 11.0.6 are getins java erros in android and net6 referencies that dont exist in net8-android 

and in browser we are using avalonia 11.0.6 with browser target, because avalonia nightly are geting erros in browser project... 

```
` 
                      
 < Project Sdk="Microsoft.NET.Sdk"  >  
	< PropertyGroup >
		< TargetFramework > net8.0 < /TargetFramework  >
		< Nullable > enable < /Nullable >
		< LangVersion > latest < /LangVersion >
		< AvaloniaUseCompiledBindingsByDefault > true < /AvaloniaUseCompiledBindingsByDefault >
	<  /PropertyGroup  > 

	< Choose > 
		< When Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' or $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'" >
			< PropertyGroup  > 
				< UseMaui >true</UseMaui >
				< UseMauiEssentials >true< /UseMauiEssentials >
				< SkipValidateMauiImplicitPackageReferences  >true <  /SkipValidateMauiImplicitPackageReferences >
			< /PropertyGroup >

			< ItemGroup >
				< PackageReference Include="Avalonia" Version="11.0.999" / >
				 < PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.999" / >
				< PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.999" / >

				< PackageReference Include="Avalonia.Maui" Version="11.0.5" / >
				< PackageReference Include="Microsoft.Maui.Controls" Version="8.0.3" / >

				< !  -- Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration. -- >
				< PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.999" / >
			< /ItemGroup >
		< /When >
		< Otherwise >
			< ItemGroup >
				< PackageReference Include="Avalonia" Version="11.0.6" / >
				< PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.6" / >
				< PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.6" / >

				< ! -- Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration. --  > 
				< PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.0.6" /  >
			< /ItemGroup > 
		< /Otherwise > 
	< /Choose > 
	
	< ItemGroup > 
		< AvaloniaResource Include="Assets\**" / > 
	< /ItemGroup > 

	< ItemGroup > 
		< PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" / > 
	< /ItemGroup >
 < /Project >





`
