### ISSUE TITLE
stable nuget package

### ISSUE THREAD

**Issue by cesarchefinho** [AvaloniaUI/AvaloniaMauiHybrid#13]
pleass publich a nuget package withou preview or beta.

this block publish avalonia applications with maui hybrid to google play store and apple store.

**Comment by maxkatz6** [comment]
> this block publish avalonia applications with maui hybrid to google play store and apple store.

How? Does Google Play/Apple Store care about .NET dependency versions?

**Comment by cesarchefinho** [comment]
yes, google and apple care for use of pre release versions.

**Comment by maxkatz6** [comment]
Done
