### ISSUE TITLE
Maui embedding to Avalonia is not working with iOS

### ISSUE THREAD

**Issue by z-eh** [AvaloniaUI/AvaloniaMauiHybrid#17]
I use the following versions:
.NET 8
Avalonia.iOS: 11.0.9
Avalonia.Maui: 11.0.9
Microsoft.Maui.Controls: 8.0.7
Microsoft.Maui.Essentials: 8.0.7

Steps to reproduce:
Follow the guide in the README.md
When you reach the point when you need to use the UseMaui<MauiApplication>() extension method you can see, that not selecting the required extension method for iOS which requires the AppDelegate instance, instead it uses the simple UseMaui method with the AppBuilder.

**Comment by z-eh** [comment]
![image](https://github.com/AvaloniaUI/AvaloniaMauiHybrid/assets/542958/25ed0d3c-41c3-4a28-ad4c-b042e9126c4a)

**Comment by maxkatz6** [comment]
Do you have `using Avalonia.Maui;` in your file? This code should be enough, and you can try it in our samples.

**Comment by z-eh** [comment]
Yes I have, that's not the issue. The issue is, that in the following part of the code:
![image](https://github.com/AvaloniaUI/AvaloniaMauiHybrid/assets/542958/be58f391-01f2-4c96-ad38-d9d3c3f307cb)
As you can see somehow the system selects the last one instead of the iOS part.

**Comment by z-eh** [comment]
I made a repo which can help to reproduce the issue: [https://github.com/z-eh/avalonia-maui-bug-repro](https://github.com/z-eh/avalonia-maui-bug-repro)

**Comment by maxkatz6** [comment]
I can build your repro with no issues
![image](https://github.com/AvaloniaUI/AvaloniaMauiHybrid/assets/3163374/3e442d65-23b1-4dd0-adad-3051ab14183a)

**Comment by maxkatz6** [comment]
@z-eh can you try to run "dotnet build" on your solution? And if there is an error - send it here. Possibly you are missing .NET workloads. 

> As you can see somehow the system selects the last one instead of the iOS part.

It's just an IDE showing the least specific option. During the build, for "net8.0-ios" project "#if IOS" branch should be selected.

**Comment by z-eh** [comment]
Hi, my workloads are fine, but something is not okay.
![image](https://github.com/AvaloniaUI/AvaloniaMauiHybrid/assets/542958/17a7e27e-f681-4527-9fc0-0f2f67a1a396)
Workloads:
![image](https://github.com/AvaloniaUI/AvaloniaMauiHybrid/assets/542958/f18ade15-f6d5-40f2-a31f-b51ad6531be6)

**Comment by z-eh** [comment]
I got the root cause of the issue.
My .NET 8 SDK was at version 8.0.200, after I upgraded it to the 8.0.201 the issues is resolved.
Thanks for the tips.
