### ISSUE TITLE
Java.Lang.IllegalArgumentException when try the sample

### ISSUE THREAD

**Issue by AlleSchonWeg** [AvaloniaUI/AvaloniaMauiHybrid#18]
Hi,
i'm going to the readme: https://github.com/AvaloniaUI/AvaloniaMauiHybrid#embedding-maui-controls-inside-of-the-avalonia-app
but when i start the android app i get an exception:

> Java.Lang.IllegalArgumentException: 'The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).'

If i comment out the maui button the project works:

> <mauiControls:Button Text="Maui Button" />

[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/AvaloniaMauiHybrid/files/14419056/AvaloniaApplication1.zip)

**Comment by maxkatz6** [comment]
Some default MAUI controls require MaterialComponents theme to be applied in the app.
You can edit what theme is used in your app:

Change your styles.xml like this:
```
<style name="MyTheme.NoActionBar" parent="@style/Theme.AppCompat.DayNight.NoActionBar">
```
to
```
<style name="MyTheme.NoActionBar" parent="Theme.MaterialComponents.DayNight.NoActionBar">
```

**Comment by maxkatz6** [comment]
Updated readme instruction. Thank you for noticing it.
