### ISSUE TITLE
Question about native behavior on iOS

### ISSUE THREAD

**Issue by davidchavezgrant** [AvaloniaUI/AvaloniaMauiHybrid#6]
As I understand it, this is an experiment, so this is not really an *issue*. 
It's a question for my own understanding -- why is it that when I run this on my local emulator (M1 MacBook, iPhone14 iOS 16.4), there are a few issues:

1. The main layout seems to be off
2. The Avalonia radio buttons don't seem to be responsive
3. There seems to be a default native style applied (the little (i) icon)

![Screenshot 2023-05-05 at 2 53 49 AM](https://user-images.githubusercontent.com/81833119/236394426-27c27fb6-86f2-4af3-a767-66f01e1af47a.jpg)
The only way I've found so far to remove the unwanted icon is to add a line to `Avalonia.MAUI.Platforms.iOS.AvaloniaViewHandler.ConnectHandler`

```csharp
platformView.TintColor = UIColor.Clear;
```

But when I run it on Android, all seems well?
![Screenshot 2023-05-05 at 2 53 53 AM](https://user-images.githubusercontent.com/81833119/236394431-d0c43046-d4c1-4134-8942-b2603c44c416.jpg)

I don't fully understand how MAUI `ViewHandler`s work, so I could be missing something obvious.

**Comment by maxkatz6** [comment]
> There seems to be a default native style applied (the little (i) icon)

I think it was a bug in old avalonia preview version. Shouldn't be an issue anymore.
